### ISSUE TITLE
Feature Request: Custom actions instruction file (appending to files)

### ISSUE THREAD

**Issue by den4uk** [c4urself/bump2version#208]
Here is the scenario:

- Version bumping would happen during CI/CD pipelines (Jenkins, Travis, etc.)
- A file is maintained in the repo, which has instruction set how to bump the version, eg:

```yaml
# bumpversion.yml
# a simple example
part: PATCH
file_edit:
    changelog:
        file_name: ./CHANGELOG.md
        action: APPEND
        text: "This fixes bug foo bar"
autoclear: true
```
> _a yaml file was only used for demonstration purposes._

This would be a useful when multiple people are working on the same repository, which has very constant push/commit rates. Normally, such results in often merges of the master/main into your feature branch due to the merge conflicts in version and changelog files. Having a file describing extra activities to perform can eliminate the need to do this, thus being able to offset these actions to be performed by the CI/CD pipelines instead.

Extended logic of the yaml with explanations:

```yaml
# bumpversion.yml
# extended example with comments
part: PATCH  # what kind of bump to perform
file_edit:  # any file edits
    changelog:  # name of the edit action
        file_name: ./CHANGELOG.md  # file name where the edit to perform
        action: APPEND  # action on the file (APPEND | OVERWRITE)
        format: "| {new_version} | {date:"%Y-%m-%d"} | {text} |"  # how to format the entry (new_version as now, {date} as datetime.today(), which can also be formatted)
        text: "This fixes bug foo bar"  # value to be written
autoclear: true  # Whether to remove these "dynamic" entries from the file, if `true` - `patch` and `text` are auto-removed from this file, leaving blank spaces on the bumped commit for new instructions to be added
```

Introducing a workflow of this kind could be a real improvement to many many people.
