### ISSUE TITLE
Using bump2version with pyproject.toml bumps gunicorn version in dependencies

### ISSUE THREAD

**Issue by nadworny** [c4urself/bump2version#219]
# Problem
We've been using the following command for quite a while without issues: `bump2version minor pyproject.toml`

Unfortunately, after adding a gunicorn dependency to poetry, the above command also bumps the version of gunicorn for some reason.

Before:
```toml
[tool.poetry]
name = "test"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"
gunicorn = "^20.1.0"
```

After command:
```toml
[tool.poetry]
name = "test"
version = "0.2.0"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.63.0"
gunicorn = "^20.2.0"
```

# Environment
Python: 3.9.4
bump2version: 1.0.1
